version: "3"
services:
  # Fontend service
  gatsby:
    container_name: gatsby
    restart: always
    build: .
    image: gatsby:latest
    ports:
      - 3000:3000
    volumes:
      - ./gatsby:/src/gatsby
  # Backend service
  strapiCMS:
    container_name: strapiCMS
    restart: always
    build: ./strapi
    image: strapi:latest
    ports:
      - 1337:1337
    volumes:
      - ./strapi:/src
    environment:
      HOST: 192.168.99.100
      DATABASE_CLIENT: mongo
      DATABASE_HOST: 192.168.99.100
      DATABASE_PORT: 27017
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
